Repository spotlibs/go-lib, pull requests merged in 2024-09, with the labels that each got.

#8 feat: pkg new middlewares and `ctx`
  ctx/metadata.go
  middleware/activity_monitor.go
  middleware/metadata_header.go
  stderr/error.go
Labels: documentation, enhancement

#9 add int to words in indonesian currency
  currency/currency.go
Labels: enhancement

#10 feat: metadata with context
  ctx/metadata.go
Labels: enhancement

#11 test: new cases for currency pkg
  currency/currency.go
  tests/currency/currency_test.go
Labels: unit test

#13 feat: logger for activity runtime worker
  go.mod
  go.sum
  log/activity.go
  log/log.go
  log/runtime.go
  log/worker.go
Labels: enhancement

#14 ref: adjusment `ctx` to reflect latest goravel
  ctx/metadata.go
  go.mod
  go.sum
  middleware/activity_monitor.go
Labels: enhancement

#15 fix: use `log` for middleware activity monitor
  middleware/activity_monitor.go
Labels: enhancement

#16 ref: implement feedback in `log` and `ctx` metadata
  ctx/metadata.go
  log/activity.go
  log/log.go
  log/runtime.go
  log/worker.go
Labels: ref

#17 feat: enhancement middleware activity monitor
  README.md
  middleware/activity_monitor.go
Labels: documentation, enhancement
